######################################################################
# Automatically generated by qmake (2.01a) vr feb. 10 04:56:00 2012
######################################################################

TEMPLATE = lib
VERSION = 1.9.1
CONFIG = dll qt
TARGET = dazeus-qt
DEPENDPATH += .
INCLUDEPATH += . ../libdazeus/include
LIBS += -L../libdazeus/lib -ldazeus

# Input
HEADERS += dazeus.h
SOURCES += dazeus.cpp
