#!/bin/sh

set -e
. version
dir=doxygenfilter-$VERSION
if [ ! -f tmp/$dir/doxygenfilter.exe ]; then
    echo "please build exe first"
    exit 1
fi
cd tmp 
docs=`ls -1d $dir/* | grep '/[A-Z][A-Z]'`
zip ../packaging/pkgs/doxygenfilter-$VERSION.NTbin.zip $dir/doxygenfilter.exe $docs
