#!/bin/sh

set -e
. version
mkdir -p tmp > /dev/null 2>&1 || true
dir=doxygenfilter-$VERSION
rm -rf tmp/$dir || true
rm -f tmp/*.deb || true
if [ ! -f packaging/pkgs/doxygenfilter-$VERSION.tar.gz ]; then
    echo "please build tar package first"
    exit 1
fi
cd tmp 
tar xzf ../packaging/pkgs/doxygenfilter-$VERSION.tar.gz
cd $dir
ed debian/changelog <<END
1 s/(.*)/($VERSION-$RELEASE)/
w
q
END

dpkg-buildpackage -us -uc -tc

cd ../..
cp tmp/*.deb packaging/pkgs
