#!/bin/sh
CONTRIBDIR="contrib"
if [ ! -d "$CONTRIBDIR" ]; then
	CONTRIBDIR="../contrib"
fi
DOXYGENFILTER="${CONTRIBDIR}/doxygenfilter-1.10/"
perl -I${DOXYGENFILTER}/lib ${DOXYGENFILTER}/bin/doxygenfilter $@
